pool:
  vmImage: 'Ubuntu 16.04'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'
- task: DownloadSecureFile@1
  inputs:
    name: configFile
    secureFile: config.json
- script: echo "Printing the secure file path" 
- script: cp $(Agent.TempDirectory)/config.json $(Build.SourcesDirectory)
- task: CondaEnvironment@1
  displayName: 'Create Conda Environment '
  inputs:
    createCustomEnvironment: true
    environmentName: azuremlsdk
    packageSpecs: 'python=3.6'
    updateConda: false
    createOptions: 'cython==0.29 urllib3<1.24'
- script: |
    pip install --user azureml.defaults azureml-sdk[automl,notebooks] scipy scikit-learn pyculiarity pytictoc
  displayName: 'Install prerequisites'
- task: AzureCLI@1
  displayName: 'Azure CLI CICD/code/pipeline.py'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python CICD/code/pipeline.py'
- task: AzureCLI@1
  displayName: 'Azure CLI CICD/code/evaluate_model.py'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python CICD/code/evaluate_model.py'
- task: AzureCLI@1
  displayName: 'Azure CLI CICD/code/register_model.py'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python CICD/code/register_model.py'
- task: AzureCLI@1
  displayName: 'Azure CLI CICD/code/create_scoring_image.py'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python CICD/code/create_scoring_image.py'
- task: AzureCLI@1
  displayName: 'Azure CLI CICD/code/aks_service_test.py'
  inputs:
    azureSubscription: 'serviceConnection'
    scriptLocation: inlineScript
    inlineScript: 'python CICD/code/aks_service_test.py'
- script: |
    python CICD/code/testing/data_test.py CICD/data_sample/predmain_bad_schema.csv
  displayName: 'Test Schema'