# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: prednet

dependencies:
  - python=3.6
  - pip

  - pip:
    - keras==2.0.8
    - theano
    - tensorflow==1.8.0
    - tensorflow-gpu==1.8.0
    - hickle
    - matplotlib
    - seaborn
    - requests
    - bs4
    - imageio
    - sklearn
    - pandas
    - azureml-sdk
    